services:
  - type: web
    name: jain-quiz
    runtime: node
    plan: free
    numInstances: 1
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST_PASSCODE
        sync: false
